//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int Cedula { get; set; }
        public string Pais { get; set; }
        public string ProvinciaEstado { get; set; }
        public string CantonDelegacion { get; set; }
        public string CalleAvenida { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
